# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TellaeServicesDialog
                                 A QGIS plugin
 Access Tellae services from QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tellae
        email                : contact@tellae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import traceback

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtGui import QIcon, QPixmap

from tellae.tellae_store import TELLAE_STORE
from tellae.utils import *

from tellae.panels import LayersPanel, ConfigPanel, AboutPanel

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "main_window.ui")
)


class TellaeServicesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(TellaeServicesDialog, self).__init__(parent)

        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.layers_panel = LayersPanel(self)
        self.config_panel = ConfigPanel(self)
        self.about_panel = AboutPanel(self)

    # dialog setup

    def setup(self):

        # progress bar starts hidden with no message
        self.set_progress_bar(True)
        self.progress_text.setText('')

        # tabs management
        self.menu_widget.setCurrentRow(0)
        self.stacked_panels_widget.setCurrentIndex(0)
        self.menu_widget.currentRowChanged['int'].connect(
            TELLAE_STORE.set_tab
        )

        self.set_menu_icons()

        # panels setup
        self.layers_panel.setup()
        self.config_panel.setup()
        self.about_panel.setup()

    def set_menu_icons(self):
        # item = self.menu_widget.item(0)
        # path = os.path.dirname(__file__) + "/../santa.svg"
        # icon = QIcon(path)
        # item.setIcon(icon)
        # item = self.menu_widget.item(1)
        # item.setIcon(QIcon(resources_path('icons', 'quick.png')))
        pass

    def start_layer_download(self, layer_name):
        self.display_message(f"Téléchargement de la couche '{layer_name}'...")
        self.set_progress_bar(True)

    def signal_end_of_layer_add(self, layer_name, exception=None):
        # display result message
        if exception is None:
            message = f"La couche '{layer_name}' a été ajoutée avec succès !"
        else:
            log(f"An error occured during layer add: {exception.__repr__()}")
            # log(str(traceback.format_exc()))
            # evaluate message depending on exception type
            try:
                raise exception
            # min zoom not respected
            except MinZoomException:
                message = f"Vous devez zoomer pour charger la couche '{layer_name}'"
            # network error message
            except RequestsException as e:
                message = f"Erreur lors du téléchargement de la couche '{layer_name}'"
            except NotImplementedError:
                message = f"La couche '{layer_name}' nécessite des fonctionalités non implémentées pour le moment"
            # generic error message
            except Exception as e:
                message = f"Erreur lors de l'ajout de la couche '{layer_name}'"
                self.display_message(message)
                self.set_progress_bar(False)
                raise e

        self.display_message(message)
        self.set_progress_bar(False)

    # primitives

    def display_message(self, message: str):
        self.progress_text.setText(message)

    def set_progress_bar(self, visible: bool):
        if visible:
            self.progress_bar.setRange(0, -0)
            self.progress_bar.setValue(-1)
        else:
            self.progress_bar.setRange(0, 100)
            self.progress_bar.setValue(0)
