# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TellaeServicesDialog
                                 A QGIS plugin
 Access Tellae services from QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tellae
        email                : contact@tellae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import traceback

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QPushButton
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtGui import QIcon, QPixmap
from PyQt5.QtWidgets import QStyle

from tellae.tellae_store import TELLAE_STORE
from tellae.models.layers import create_layer, create_custom_layer
from tellae.utils import *
from tellae.utils.utils import fill_table_widget, getBinaryName
from tellae.services.project import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "main_window.ui")
)


class TellaeServicesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(TellaeServicesDialog, self).__init__(parent)

        self.selected_theme = "Tous"
        self.layers = []

        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # progress bar starts hidden
        self.set_progress_bar(False)

        self.progress_text.setText('')

        # tab management
        self.menu_widget.setCurrentRow(0)
        self.stacked_panels_widget.setCurrentIndex(0)
        self.menu_widget.currentRowChanged['int'].connect(
            TELLAE_STORE.set_tab)

        self.set_menu_icons()

    def set_menu_icons(self):
        return
        item = self.menu_widget.item(0)
        path = os.path.dirname(__file__) + "/../santa.svg"
        icon = QIcon(path)
        item.setIcon(icon)
        return
        item = self.menu_widget.item(1)
        item.setIcon(QIcon(resources_path('icons', 'quick.png')))
        item = self.menu_widget.item(2)
        item.setIcon(QIcon(resources_path('icons', 'edit.png')))
        item = self.menu_widget.item(3)
        item.setIcon(QIcon(resources_path('icons', 'open.png')))
        item = self.menu_widget.item(4)
        item.setIcon(QIcon(resources_path('icons', 'general.svg')))
        item = self.menu_widget.item(5)
        item.setIcon(QIcon(resources_path('icons', 'info.png')))

    def set_auth_button_text(self, user):
        if user is None:
            text = "Login"
        else:
            text = f'{user["firstName"]} {user["lastName"]}'

        self.authButton.setText(text)

    def display_message(self, message: str):
        self.progress_text.setText(message)

    def set_progress_bar(self, visible: bool):
        if visible:
            self.progress_bar.setRange(0, -0)
            self.progress_bar.setValue(-1)
        else:
            self.progress_bar.setRange(0, 100)
            self.progress_bar.setValue(0)

    def create_theme_selector(self):
        # set list of layers
        self.themeSelector.addItems(["Tous"] + TELLAE_STORE.themes)

        # set default selection to "all"
        self.themeSelector.setCurrentText("Tous")

        # add listener on update event
        self.themeSelector.currentTextChanged.connect(self.update_theme)

    def update_theme(self, new_theme):
        # update selected theme
        self.selected_theme = new_theme

        # update layers table
        self.set_layers_table()

    def set_layers_table(self):
        # get table widget
        table = self.tableWidget

        # get list of layers to display
        self.layers = TELLAE_STORE.get_filtered_layer_summary(self.selected_theme)

        # action slot

        def action_slot(table_widget, row_ix, col_ix, _, __):
            btn = QPushButton(table)
            btn.setIcon(self.style().standardIcon(QStyle.SP_DialogSaveButton))
            btn.clicked.connect(lambda state, x=row_ix: self.add_layer(x))
            table_widget.setCellWidget(row_ix, col_ix, btn)

        # setup table headers
        # total table length is 791, scroll bar is 16 => header width must total to 775
        headers = [
            {"text": "Nom", "value": lambda x: x["name"][TELLAE_STORE.locale], "width": 355},
            {
                "text": "Date",
                "value": lambda x: TELLAE_STORE.datasets_summary[x["main_dataset"]].get("date", ""),
                "width": 80,
                "align": Qt.AlignCenter,
            },
            {
                "text": "Source",
                "value": lambda x: TELLAE_STORE.datasets_summary[x["main_dataset"]][
                    "provider_name"
                ],
                "width": 280,
            },
            {"text": "Actions", "value": "actions", "width": 60, "slot": action_slot},
        ]

        fill_table_widget(table, headers, self.layers)


    def add_layer(self, index):
        layer_item = self.layers[index]
        layer_name = layer_item.get("name", dict()).get(TELLAE_STORE.locale, "Unnamed")

        try:
            qgs_kite_layer = create_layer(layer_item)
            qgs_kite_layer.add_to_qgis()

        except Exception as e:
            self.signal_end_of_layer_add(layer_name, e)

    def start_layer_download(self, layer_name):
        self.display_message(f"Téléchargement de la couche '{layer_name}'...")
        self.set_progress_bar(True)

    def signal_end_of_layer_add(self, layer_name, exception=None):
        # display result message
        if exception is None:
            message = f"La couche '{layer_name}' a été ajoutée avec succès !"
        else:
            log(f"An error occured during layer add: {exception.__repr__()}")
            # log(str(traceback.format_exc()))
            # evaluate message depending on exception type
            try:
                raise exception
            # min zoom not respected
            except MinZoomException:
                message = f"Vous devez zoomer pour charger la couche '{layer_name}'"
            # network error message
            except RequestsException as e:
                message = f"Erreur lors du téléchargement de la couche '{layer_name}'"
            except NotImplementedError:
                message = f"La couche '{layer_name}' nécessite des fonctionalités non implémentées pour le moment"
            # generic error message
            except Exception as e:
                message = f"Erreur lors de l'ajout de la couche '{layer_name}'"
                raise e
        self.display_message(message)

        # remove loader
        self.set_progress_bar(False)

    def setup_project_selector(self):
        project_names = [project.get("uuid") for project in TELLAE_STORE.user["_ownedProjects"]]

        # set list of layers
        self.projectSelector.addItems(project_names)

        # add listener on update event
        self.projectSelector.currentTextChanged.connect(select_project)


    def set_project_spatial_data_table(self):
        table = self.projectLayersTable

        spatial_data = TELLAE_STORE.current_project["spatial_data"]

        def action_slot(table_widget, row_ix, col_ix, _, __):
            btn = QPushButton(table_widget)
            btn.setText("Add")
            btn.clicked.connect(lambda state, x=row_ix: self.add_spatial_data(x))
            table_widget.setCellWidget(row_ix, col_ix, btn)

        # setup table headers
        # total table length is 721, scroll bar is 16 => header width must total to 705
        headers = [
            {"text": "Nom", "value": lambda x: getBinaryName(x, with_extension=False), "width": 729},
            {"text": "Actions", "value": "actions", "width": 60, "slot": action_slot},
        ]

        fill_table_widget(table, headers, spatial_data)

    def add_spatial_data(self, row_idx):
        binary = TELLAE_STORE.current_project["spatial_data"][row_idx]
        name = getBinaryName(binary, with_extension=False)

        def handler(result):
            try:
                qgs_kite_layer = create_custom_layer(result["content"], name)
                qgs_kite_layer.add_to_qgis()

            except Exception as e:
                log(e)
                # TELLAE_STORE.main_dialog.signal_end_of_layer_add(name, e)
                raise e


        get_project_binary_from_hash(binary["hash"], "spatial_data", handler, to_json=False)